from controlgym.envs.linear_control import LinearControlEnv
from controlgym.envs.pde import PDE
from controlgym.envs.allen_cahn import AllenCahnEnv
from controlgym.envs.burgers import BurgersEnv
from controlgym.envs.cahn_hilliard import CahnHilliardEnv
from controlgym.envs.fisher import FisherEnv
from controlgym.envs.ginzburg_landau import GinzburgLandauEnv
from controlgym.envs.kuramoto_sivashinsky import KuramotoSivashinskyEnv
from controlgym.envs.schrodinger import SchrodingerEnv
from controlgym.envs.wave import WaveEnv
from controlgym.envs.convection_diffusion_reaction import ConvectionDiffusionReactionEnv
from controlgym.envs.korteweg_de_vries import KortewegDeVriesEnv
from controlgym.envs.registrations import make